### ISSUE TITLE
portainer 无法打开呢

### ISSUE THREAD

**Issue by goodppgood** [h31105/trojan_v2_docker_onekey#10]
http://name:9080

显示
500 Internal Privoxy Error
Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

**Comment by h31105** [comment]
> http://name:9080
> 
> 
> 
> 显示
> 
> 500 Internal Privoxy Error
> 
> Privoxy encountered an error while processing your request:
> 
> 
> 
> Could not load template file no-server-data or one of its included components.
> 
> 
> 
> Please contact your proxy administrator.
> 
> 
> 
> If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory).

用#docker ps --all 看一下portainer容器的状态 是否正常

**Comment by goodppgood** [comment]
![Uploading image.png
![Uploading 微信图片_20201009150110.png…]()
…]()
3.脚本版本就是今天装的最新，os是Debian10， gcp上面

**Comment by h31105** [comment]
> 
> 
> ![微信图片_20201009150110](https://user-images.githubusercontent.com/57130097/95553393-10722480-0a41-11eb-9c4b-165257629895.png)
> 
> 
> 
> 3.脚本版本就是今天装的最新，os是Debian10， gcp上面
> 
> 
> 
> 
> 
> 还是无法打开portainer 

#systemctl stop firewalld
#lsof -i
#systemctl restart docker
然后再试试
