### ISSUE TITLE
安装时服务无法启动。卸载重装依旧。

### ISSUE THREAD

**Issue by jindx0713** [h31105/trojan_v2_docker_onekey#11]
![image](https://user-images.githubusercontent.com/30382973/95567504-9ac48380-0a55-11eb-8cdc-861dcd9e4cc2.png)

**Comment by h31105** [comment]
> ![image](https://user-images.githubusercontent.com/30382973/95567504-9ac48380-0a55-11eb-8cdc-861dcd9e4cc2.png)
> 
> 
#systemctl start tls-shunt-proxy
#journalctl -u tls-shunt-proxy.service
日志发一下

**Comment by jindx0713** [comment]
![image](https://user-images.githubusercontent.com/30382973/95570483-8edac080-0a59-11eb-99b2-e0fd75dc2d0c.png)
![image](https://user-images.githubusercontent.com/30382973/95570500-9732fb80-0a59-11eb-8f4d-ee07453fbd9a.png)

**Comment by h31105** [comment]
> ![image](https://user-images.githubusercontent.com/30382973/95570483-8edac080-0a59-11eb-99b2-e0fd75dc2d0c.png)
> 
> ![image](https://user-images.githubusercontent.com/30382973/95570500-9732fb80-0a59-11eb-8f4d-ee07453fbd9a.png)
> 
> 

service 启动失败，请使用命令 
sudo setcap "cap_net_bind_service=+ep" /usr/local/bin/tls-shunt-proxy 给 tls-shunt-proxy 赋予 CAP_NET_BIND_SERVICE 的 capability ，然后 
sudo -u tls-shunt-proxy /usr/local/bin/tls-shunt-proxy -config /etc/tls-shunt-proxy/config.yaml 运行

参考上述步骤，试试看能否正常启动

**Comment by jindx0713** [comment]
![image](https://user-images.githubusercontent.com/30382973/95579396-2515e300-0a68-11eb-95de-4dde67f5342e.png)

**Comment by h31105** [comment]
> ![image](https://user-images.githubusercontent.com/30382973/95579396-2515e300-0a68-11eb-95de-4dde67f5342e.png)
> 
> 

应该正常了

**Comment by h31105** [comment]
> 第二个解决方法无效，第一个给了权限之后就OK了。

![image](https://user-images.githubusercontent.com/38588395/95602746-eee85b80-0a87-11eb-815a-9bc7d04d57d8.png)

**Comment by jindx0713** [comment]
问题是什么原因导致的？脚本的问题，还是系统的问题？
我的vps是重新安装的centos7，只是yum update了一下。

**Comment by h31105** [comment]
> 问题是什么原因导致的？脚本的问题，还是系统的问题？
> 我的vps是重新安装的centos7，只是yum update了一下。

可能跟系统模版的**安全策略**有关系，我这里的几台vps，centos 7 ，dedian 10，Ubuntu 18 都没碰到这个问题，但你这个问题，的确有人碰到过（可能小概率？）。

**Comment by h31105** [comment]
> 脚本能修复一下不？
> 另外，openclash在软路由上面已经可以支持Trojan-go了。
> 
> 按照以下格式就可以了
> 
> * name: "trojan-sg"
>   type: trojan
>   server: host
>   port: 443
>   password: password
>   udp: true
>   sni: host

加tg群讨论 https://t.me/trojanv2
