### ISSUE TITLE
安装BBR PLUS后，无法连接

### ISSUE THREAD

**Issue by jindx0713** [h31105/trojan_v2_docker_onekey#12]
装了bbr plus后，没办法进行连接了。

journalctl -u tls-shunt-proxy.service 显示内容如下：
![image](https://user-images.githubusercontent.com/30382973/95643105-701f0d00-0adf-11eb-8bd0-ffcffac7102b.png)

重启tsp和trojan容器也没响应。
伪装网站一并打不开。

**Comment by h31105** [comment]
@jindx0713 docker 当前版本不兼容 4.x bbr plus 内核

**Comment by jindx0713** [comment]
收到。

**Comment by jindx0713** [comment]
把内核换回来之后还是无法连接……

**Comment by h31105** [comment]
@jindx0713 通过脚本升级选项，走一边升级docker的流程

**Comment by jindx0713** [comment]
emmmm.升级了一遍，重启了一遍，问题没解决。

什么地方的日志可以看出来问题？

**Comment by h31105** [comment]
> emmmm.升级了一遍，重启了一遍，问题没解决。
> 
> 
> 
> 什么地方的日志可以看出来问题？

收集以下信息
systemctl status tls-shunt-proxy
systemctl status docker
docker ps --all
lsof -i
uname -a
还有脚本运行后是否有错误提示信息

**Comment by jindx0713** [comment]
![image](https://user-images.githubusercontent.com/30382973/95644213-a95b7b00-0ae7-11eb-89d2-806143dfc7f4.png)

**Comment by h31105** [comment]
> ![image](https://user-images.githubusercontent.com/30382973/95644213-a95b7b00-0ae7-11eb-89d2-806143dfc7f4.png)
> 
> 

没看出问题，一切正常啊
你检查一下防火墙

**Comment by h31105** [comment]
加tg群 https://t.me/trojanv2
