### ISSUE TITLE
安装所有容器时都会提示一样的错误（LXC）

### ISSUE THREAD

**Issue by zyp997** [h31105/trojan_v2_docker_onekey#13]
我使用的是ipv6的debain10服务器。第一步安装TLS-Shunt-Proxy时是没问题的，能够正确解析到ipv6的地址。安装所有容器时都会提示一样的错误。
如下：
docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused \"join session keyring: create session key: disk quota exceeded\"": unknown.
[错误]  容器安装 失败

**Comment by h31105** [comment]
> 我使用的是ipv6的debain10服务器。第一步安装TLS-Shunt-Proxy时是没问题的，能够正确解析到ipv6的地址。安装所有容器时都会提示一样的错误。
> 如下：
> docker: Error response from daemon: OCI runtime create failed: container_linux.go:349: starting container process caused "process_linux.go:449: container init caused "join session keyring: create session key: disk quota exceeded"": unknown.
> [错误] 容器安装 失败

uname -a 看一下当前内核，如果内核版本过低，建议apt update 升级内核后（或者直接通过bbr脚本安装5.x bbr/4.14.128 bbr plus内核）再试

**Comment by zyp997** [comment]
内核是  Linux geust997 4.20.8-1.el7.elrepo.x86_64 #1 SMP Tue Feb 12 18:03:03 EST 2019 x86_64 GNU/Linux
是lxc架构的。能有解决的方法吗？

**Comment by h31105** [comment]
@zyp997 抱歉，这个…基本上很难，建议使用非docker方式部署脚本。
