### ISSUE TITLE
FinalShell二维码显示异常

### ISSUE THREAD

**Issue by qiaohewei** [h31105/trojan_v2_docker_onekey#15]
<img width="789" alt="Xnip2020-10-27_15-31-50" src="https://user-images.githubusercontent.com/21193340/97270133-98419680-1869-11eb-819f-759743c17bb0.png">

**Comment by h31105** [comment]
二维码由 asciiutf8 方式输出，其输出效果很大程度上取决于终端英文字体的“模拟点阵效果”。
建议更换不同的英文字体再试。（建议选择“Consolas”）

**Comment by qiaohewei** [comment]
OK,Thanks，更换终端后显示正常。
