### ISSUE TITLE
docker 开始有限制了，能否出个能自动更新 trojan-go 的非 docker 版……

### ISSUE THREAD

**Issue by 9211314** [h31105/trojan_v2_docker_onekey#17]
docker: Error response from daemon: toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit.

**Comment by h31105** [comment]
@9211314 这个没关系， 暂时排队拉取忍忍吧，船新版本还在写…

**Comment by 9211314** [comment]
Thank you
