### ISSUE TITLE
docker 在 centos8 启动失败

### ISSUE THREAD

**Issue by heysky** [h31105/trojan_v2_docker_onekey#18]
Centos8系统，安装trojan的时候，docker 启动失败。错误信息：
/usr/bin/containerd: symbol lookup error: /usr/bin/containerd: undefined symbol: seccomp_api_set

根据 https://github.com/containerd/containerd/issues/4619，需要升级 libseccomp to 2.4.x。“yum update libseccomp”
麻烦可以加到安装脚本中吗？

**Comment by h31105** [comment]
好的，谢谢

> Centos8系统，安装trojan的时候，docker 启动失败。错误信息：
> /usr/bin/containerd: symbol lookup error: /usr/bin/containerd: undefined symbol: seccomp_api_set
> 
> 根据 [https://github.com/containerd/containerd/issues/4619，需要升级](https://github.com/containerd/containerd/issues/4619%EF%BC%8C%E9%9C%80%E8%A6%81%E5%8D%87%E7%BA%A7) libseccomp to 2.4.x。“yum update libseccomp”
> 麻烦可以加到安装脚本中吗？
