### ISSUE TITLE
十分好用，不过能否在查看参数时加上订阅链接

### ISSUE THREAD

**Issue by sp960817** [h31105/trojan_v2_docker_onekey#2]
这样就更加方便，提供下建议谢谢大佬

**Comment by h31105** [comment]
谢谢，目前这个脚本，还有很多地方还没写 等后面有时间一起补上吧。

**Comment by bsharkl** [comment]
非常棒，docker版非常方便，不影响系统本身的运作。

**Comment by h31105** [comment]
v0.96 客户端配置信息中已添加 Trojan-Go 和V2Ray 的配置链接
