### ISSUE TITLE
此脚本VMess 新版格式连不了网，只能使用VMess旧版链接

### ISSUE THREAD

**Issue by qnyblog** [h31105/trojan_v2_docker_onekey#27]
此脚本VMess 新版格式连不了网，只能使用VMess旧版链接 (Ubuntu 20.04)

**Comment by h31105** [comment]
@qnyblog 各个客户端对分享链接格式的兼容程度不同，（VMess新版格式，需要Qv2ray客户端）请自行适配。

**Comment by qnyblog** [comment]
好的，非常感谢。当时VMess新版格式我用的v2rayN客户端

**Comment by qnyblog** [comment]
请问VLESS 新版格式也是只能使用Qv2ray客户端吗？谢谢

**Comment by h31105** [comment]
@qnyblog VLESS v2rayN应该没问题，（Qv2ray 我没试过

**Comment by qnyblog** [comment]
好的，非常感谢
