### ISSUE TITLE
此脚本trojan-go tcp模式下被封

### ISSUE THREAD

**Issue by balabala4021** [h31105/trojan_v2_docker_onekey#28]
自建server主要玩外服游戏与奈飞，server安全措施做足了，client无任何国产software or app，表现为ipcheck和dnscheck均为外网ip，dns leak test无洩露，伪装web被封于是iplookup，结果显示ipaddress被导向了已被墙的陌生vultr ip，此时ssh与外网能访问但不流畅，平时养成的习惯会不定时会访问fake web，细思恐极

**Comment by h31105** [comment]
@balabala4021 从描述来看，web被封-->nslookup 为“陌生被封”的vultr ip，这个过程属于dns解析，如果自己没改dns记录，那可能就是dns污染劫持了，另外，ssh能连接上“被墙”的服务器，细思极恐

**Comment by h31105** [comment]
另外建议部署后，不要刻意的去做一些“画蛇添足”的“伪装行为”…

**Comment by balabala4021** [comment]
@h31105 谢谢建议，重新部署了，script简单高效，又可以游戏了
