### ISSUE TITLE
域名DNS解析IP与本机IP匹配，去总是错误

### ISSUE THREAD

**Issue by qnyblog** [h31105/trojan_v2_docker_onekey#29]
[错误]  请确保域名添加了正确的 A/AAAA 记录，否则将无法正常连接
[错误]  域名DNS 解析IP 与 本机IP 不匹配将导致 SSL 证书申请失败，是否继续安装？（Y/N）[N]

**Comment by h31105** [comment]
> [错误] 请确保域名添加了正确的 A/AAAA 记录，否则将无法正常连接
> [错误] 域名DNS 解析IP 与 本机IP 不匹配将导致 SSL 证书申请失败，是否继续安装？（Y/N）[N]

可能是dns解析延迟导致，稍后再试，或者输入Y继续

**Comment by qnyblog** [comment]
非常感谢
