### ISSUE TITLE
DNS解锁问题

### ISSUE THREAD

**Issue by ghost** [h31105/trojan_v2_docker_onekey#31]
请问解锁Netflix的DNS如何设置？v2ray改哪？

**Comment by h31105** [comment]
参考这个试试：
https://github.com/h31105/deployX.sh/issues/20

**Comment by ghost** [comment]
这个脚本似乎并没有提供指定DNS的选项，只是将dns指向本机127.0.0.1解析，那我本机不是原生ip要怎么指定为解锁的dns呢？

**Comment by h31105** [comment]
> 这个脚本似乎并没有提供指定DNS的选项，只是将dns指向本机127.0.0.1解析，那我本机不是原生ip要怎么指定为解锁的dns呢？

你如果主机用Dnsmasq解锁，docker dns就指向127.0.0.1
如果主机直接用dns解锁，那docker dns就直接指向解锁dns

脚本没有这部分内容，需要手动操作

**Comment by h31105** [comment]
> > 这个脚本似乎并没有提供指定DNS的选项，只是将dns指向本机127.0.0.1解析，那我本机不是原生ip要怎么指定为解锁的dns呢？
> 
> 你如果主机用Dnsmasq解锁，docker dns就指向127.0.0.1
> 如果主机直接用dns解锁，那docker dns就直接指向解锁dns
> 
> 脚本没有这部分内容，需要手动操作

但默认情况下，只需要主机设置解锁dns后，docker应该会使用主机设置的dns，不需要额外设置。

**Comment by ghost** [comment]
> > 这个脚本似乎并没有提供指定DNS的选项，只是将dns指向本机127.0.0.1解析，那我本机不是原生ip要怎么指定为解锁的dns呢？
> 
> 你如果主机用Dnsmasq解锁，docker dns就指向127.0.0.1
> 如果主机直接用dns解锁，那docker dns就直接指向解锁dns
> 
> 脚本没有这部分内容，需要手动操作

'如果主机直接用dns解锁，那docker dns就直接指向解锁dns'
请问针对这部分，docker dns 指向v2ray   要怎么写？dns 127.0.0.1写成解锁dns就可以吗？
docker run -d --network host --**_dns 127.0.0.1_** --name Trojan-Go --restart=always -v /etc/trojan-go:/etc/trojan-go teddysun/trojan-go

**Comment by h31105** [comment]
> > > 这个脚本似乎并没有提供指定DNS的选项，只是将dns指向本机127.0.0.1解析，那我本机不是原生ip要怎么指定为解锁的dns呢？
> > 
> > 
> > 你如果主机用Dnsmasq解锁，docker dns就指向127.0.0.1
> > 如果主机直接用dns解锁，那docker dns就直接指向解锁dns
> > 脚本没有这部分内容，需要手动操作
> 
> '如果主机直接用dns解锁，那docker dns就直接指向解锁dns'
> 请问针对这部分，docker dns 指向v2ray 要怎么写？dns 127.0.0.1写成解锁dns就可以吗？
> docker run -d --network host --**_dns 127.0.0.1_** --name Trojan-Go --restart=always -v /etc/trojan-go:/etc/trojan-go teddysun/trojan-go

进群讨论吧 https://t.me/trojanv2

**Comment by ghost** [comment]
bot无法验证，进不去
