### ISSUE TITLE
安装成功启动失败

### ISSUE THREAD

**Issue by llity** [h31105/trojan_v2_docker_onekey#5]
[错误]  tls-shunt-proxy 未启动 
[错误]  检测到 tls-shunt-proxy 服务异常，正在尝试修
重新安装后，安装 watchtower 都会出现错误

**Comment by h31105** [comment]
> [错误]  tls-shunt-proxy 未启动 
> 
> [错误]  检测到 tls-shunt-proxy 服务异常，正在尝试修
> 
> 重新安装后，安装 watchtower 都会出现错误

有更详细的信息提供吗？比如OS 内核版本？
另外 
systemctl status tls-shunt-proxy
systemctl status docker
的信息也提供一下

**Comment by h31105** [comment]
> [错误]  tls-shunt-proxy 未启动 
> 
> [错误]  检测到 tls-shunt-proxy 服务异常，正在尝试修
> 
> 重新安装后，安装 watchtower 都会出现错误

请问 你的问题解决了吗？
