### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by miles-lin** [h31105/trojan_v2_docker_onekey#7]
脚本v1.163
1、安装脚本第三条“安装V2Ray TCP/WS 代理（容器）”，如果安装TCP及WS全部选择vless协议，v2ray不能连接到服务器。
2、安装脚本第三条“安装V2Ray TCP/WS 代理（容器）”选择安装为vmess协议，其生成的共享链接中的额外ID，与服务器配置文件中的额外ID不相符

**Comment by h31105** [comment]
> 脚本v1.163
> 1、安装脚本第三条“安装V2Ray TCP/WS 代理（容器）”，如果安装TCP及WS全部选择vless协议，v2ray不能连接到服务器。

经过验证，应该是没问题的，由于VLESS目前没有出台分享链接规范，请仔细核对配置信息，确认客户端信息是否填写正确

> 2、安装脚本第三条“安装V2Ray TCP/WS 代理（容器）”选择安装为vmess协议，其生成的共享链接中的额外ID，与服务器配置文件中的额外ID不相符

分享链接中的AlterID固定为6 是有意为之，脚本部署的服务端AlterID为10，根据VMess协议配置规则，客户端AlterID只要小于服务端即可（但不能为0，4.28后AlterID=0 会开启VMessAEAD加密）

**Comment by h31105** [comment]
请注意：
配置信息中列出的各协议 **监听端口** 不属于客户端配置
客户端配置中服务器地址和端口，统一为TLS域名和443端口

**Comment by miles-lin** [comment]
脚本第5条 安装 Portainer（Web管理容器）后
通过域名加端口9080访问，页面不能访问提示此网站无法提供安全连接

**Comment by h31105** [comment]
这个我在ReadMe里面没交代清楚，等会补上
Portainer由于不经过TSP分流，其的默认访问应该为http://VPSIP:9080

**Comment by h31105** [comment]
> 脚本第5条 安装 Portainer（Web管理容器）后
> 通过域名加端口9080访问，页面不能访问提示此网站无法提供安全连接

这个我在ReadMe里面没交代清楚，等会补上
Portainer由于不经过TSP分流，其的默认访问应该为http://VPSIP:9080

**Comment by miles-lin** [comment]
> > 脚本第5条安装Portainer（Web管理容器）后
> > 通过域名加端口9080访问，页面不能访问提示此网站无法提供安全连接
> 
> 这个我在ReadMe里面可能没交代清楚
> Portainer由于不经过TSP分流，其的访问应该为**HTTP**：// <域名或者IP>：9080（非HTTPS）
> 如果需要HTTPS的加密访问，需要在Portainer中配置证书。

感谢解答！是我没注意，是chrome浏览器强制修改为HTTPS进行访问，chrome可以用通过IP访问。
