### ISSUE TITLE
更改v2ray配置

### ISSUE THREAD

**Issue by nichwang88** [h31105/trojan_v2_docker_onekey#9]
请问部署了v2ray以后，能手动更改配置中的 UUID、AlterID、Path吗？

**Comment by h31105** [comment]
> 请问部署了v2ray以后，能手动更改配置中的 UUID、AlterID、Path吗？

分两种情况：
1. 可以通过脚本选项 8 修改上述内容
2. 完全自定义修改的话，需要修改V2Ray配置文件（/etc/v2ray/config.json）和TSP配置文件中v2ray的path的部分（/etc/tls-shunt-proxy/config.yaml）后重启V2Ray容器和TSP服务（重启命令参考readme.me）

**Comment by nichwang88** [comment]
多谢指导，我试试！

**Comment by nichwang88** [comment]
已搞定！
